### PR TITLE
build: update redis pecl package to 6.1.0

### PR DESCRIPTION
**Pull request by tobybellwood**

### CODE REVIEW

**Comment by sjerdo** [comment]
This breaks support for symfony/cache < [v6.4.12](https://github.com/symfony/cache/releases/tag/v6.4.12)

```
2024-11-27T04:22:00.897978131Z PHP Fatal error:  Declaration of Symfony\Component\Cache\Traits\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false in /app/vendor/symfony/cache/Traits/Redis6Proxy.php on line 519
2024-11-27T04:22:00.903295801Z Symfony\Component\ErrorHandler\Error\FatalError {#41441
2024-11-27T04:22:00.903893651Z   #message: "Compile Error: Declaration of Symfony\Component\Cache\Traits\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false"
2024-11-27T04:22:00.904012611Z   #code: 0
2024-11-27T04:22:00.904024621Z   #file: "./vendor/symfony/cache/Traits/Redis6Proxy.php"
2024-11-27T04:22:00.904030761Z   #line: 519
2024-11-27T04:22:00.904036011Z   -error: array:4 [
2024-11-27T04:22:00.904041091Z     "type" => 64
2024-11-27T04:22:00.904046461Z     "message" => "Declaration of Symfony\Component\Cache\Traits\Redis6Proxy::hSet($key, $member, $value): Redis|int|false must be compatible with Redis::hSet(string $key, mixed ...$fields_and_vals): Redis|int|false"
2024-11-27T04:22:00.904051341Z     "file" => "/app/vendor/symfony/cache/Traits/Redis6Proxy.php"
2024-11-27T04:22:00.904056371Z     "line" => 519
2024-11-27T04:22:00.904061541Z   ]
2024-11-27T04:22:00.904066311Z }
```

Upgrading to at least version v6.4.12 fixes the issues

**Comment by tobybellwood** [comment]
Oof, out of interest, does that cause an issue with any pinned dependencies (ie Drupal/laravel) or is it easily upgraded?

If it's more widespread, we can always look at downgrading.

**Comment by sjerdo** [comment]
Fortunately, this is easily upgraded

Our auto deploys failed this morning, updating the package with `composer update symfony/cache` fixed the issue

**Comment by tobybellwood** [comment]
Thanks for the update! Will keep an eye on it, and sorry for the inconvenience!

**Pull request merged**
